language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - node
install:
  - yarn
script:
- yarn workspace typed-ecstasy test:ci
after_success: 'yarn workspace typed-ecstasy coveralls'
